# 현재 의도를 살리되 문제점 해결
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # --- 1단계: 군수물자 보급 ---
  - name: 'python:3.11'
    id: 'Install Dependencies'
    entrypoint: 'pip'
    args: ['install', '-e', '.[test,dev]']

  # --- 2단계: 코드 품질 검사 (개선됨) ---
  - name: 'python:3.11'
    id: 'Lint Code'
    entrypoint: 'ruff'
    args: ['check', '.']  # ✅ 전체 프로젝트 검사
    waitFor: ['Install Dependencies']

  # --- 3단계: 단위 테스트 ---
  - name: 'python:3.11'
    id: 'Run Unit Tests'
    entrypoint: 'python'
    args: ['-m', 'pytest', '-v']  # ✅ verbose 출력 추가
    waitFor: ['Lint Code']  # ✅ 순차 실행 유지

timeout: '1200s'
