# Cloud Build가 로그를 Cloud Logging에만 기록하도록 명시
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # --- 1단계: 의존성 설치 ---
  - name: 'python:3.11'
    id: 'Install Dependencies'
    entrypoint: 'pip'
    args: ['install', '-e', '.[test,dev]']

  # --- 2단계: 코드 린팅만 유지 ---
  - name: 'python:3.11'
    id: 'Lint Code'
    entrypoint: 'python'
    args: ['-m', 'ruff', 'check', '.']
    waitFor: ['Install Dependencies']

  # --- 3단계: 단위 테스트 ---
  - name: 'python:3.11'
    id: 'RUN_UNIT_TESTS'
    entrypoint: 'python'
    args: ['-m', 'pytest', '-v']
    waitFor: ['Install Dependencies']

  # --- 4단계: Vertex AI 배포 ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Hephaestus Agent'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "All checks passed. Deploying Hephaestus-Alpha to Vertex AI Reasoning Engine..."
        gcloud beta ai reasoning-engines create \
          --display-name="hephaestus-alpha" \
          --location="us-central1" \
          --project="$$PROJECT_ID" \
          --package-path="." \
          --python-module="argo.agents.hephaestus" \
          --class-name="HephaestusAgent"
    waitFor: ['Lint Code', 'RUN_UNIT_TESTS']

timeout: '1200s'
